# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Jean Shen"
description: > # this means to ignore newlines until "email:"
   a UX designer based in HK

email: jeanshen.m@gmail.com
logo: "/assets/images/logo.png"
blog-logo: "/assets/images/logo.png"
float_logo: "/assets/images/logo.png"

# blog cover
cover: "/assets/images/forest-haze-hd-wallpaper-39811.jpg"

name: 'Jean Shen'
author: 'Jean Shen'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://www.jeanshen.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon:	email
#    url:	shenmengjing@gmail.com
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: instagram
    url: https://instagram.com/kidultyoung/
    desc: Connect with me on Instagram

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
